/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GetRouteImport } from './routes/get'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShareRouteImport } from './routes/share'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as GetIndexRouteImport } from './routes/get.index'
import { Route as GetProviderRouteImport } from './routes/get.$provider'
import { Route as GoAssignmentIdRouteImport } from './routes/go.$assignmentId'
import { Route as ITokenRouteImport } from './routes/i.$token'
import { Route as ShareIndexRouteImport } from './routes/share.index'
import { Route as ShareProviderRouteImport } from './routes/share.$provider'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GetRoute = GetRouteImport.update({
  id: '/get',
  path: '/get',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const GetIndexRoute = GetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GetRoute,
} as any)
const GetProviderRoute = GetProviderRouteImport.update({
  id: '/$provider',
  path: '/$provider',
  getParentRoute: () => GetRoute,
} as any)
const GoAssignmentIdRoute = GoAssignmentIdRouteImport.update({
  id: '/go/$assignmentId',
  path: '/go/$assignmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ITokenRoute = ITokenRouteImport.update({
  id: '/i/$token',
  path: '/i/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIndexRoute = ShareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShareRoute,
} as any)
const ShareProviderRoute = ShareProviderRouteImport.update({
  id: '/$provider',
  path: '/$provider',
  getParentRoute: () => ShareRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/dashboard': typeof DashboardRoute
  '/get': typeof GetRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/share': typeof ShareRouteWithChildren
  '/terms': typeof TermsRoute
  '/get/$provider': typeof GetProviderRoute
  '/go/$assignmentId': typeof GoAssignmentIdRoute
  '/i/$token': typeof ITokenRoute
  '/share/$provider': typeof ShareProviderRoute
  '/get/': typeof GetIndexRoute
  '/share/': typeof ShareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/get/$provider': typeof GetProviderRoute
  '/go/$assignmentId': typeof GoAssignmentIdRoute
  '/i/$token': typeof ITokenRoute
  '/share/$provider': typeof ShareProviderRoute
  '/get': typeof GetIndexRoute
  '/share': typeof ShareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/dashboard': typeof DashboardRoute
  '/get': typeof GetRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/share': typeof ShareRouteWithChildren
  '/terms': typeof TermsRoute
  '/get/$provider': typeof GetProviderRoute
  '/go/$assignmentId': typeof GoAssignmentIdRoute
  '/i/$token': typeof ITokenRoute
  '/share/$provider': typeof ShareProviderRoute
  '/get/': typeof GetIndexRoute
  '/share/': typeof ShareIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/community-guidelines'
    | '/dashboard'
    | '/get'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/share'
    | '/terms'
    | '/get/$provider'
    | '/go/$assignmentId'
    | '/i/$token'
    | '/share/$provider'
    | '/get/'
    | '/share/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/community-guidelines'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/get/$provider'
    | '/go/$assignmentId'
    | '/i/$token'
    | '/share/$provider'
    | '/get'
    | '/share'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/community-guidelines'
    | '/dashboard'
    | '/get'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/share'
    | '/terms'
    | '/get/$provider'
    | '/go/$assignmentId'
    | '/i/$token'
    | '/share/$provider'
    | '/get/'
    | '/share/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  DashboardRoute: typeof DashboardRoute
  GetRoute: typeof GetRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ShareRoute: typeof ShareRouteWithChildren
  TermsRoute: typeof TermsRoute
  GoAssignmentIdRoute: typeof GoAssignmentIdRoute
  ITokenRoute: typeof ITokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get': {
      id: '/get'
      path: '/get'
      fullPath: '/get'
      preLoaderRoute: typeof GetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get/': {
      id: '/get/'
      path: '/'
      fullPath: '/get/'
      preLoaderRoute: typeof GetIndexRouteImport
      parentRoute: typeof GetRoute
    }
    '/get/$provider': {
      id: '/get/$provider'
      path: '/$provider'
      fullPath: '/get/$provider'
      preLoaderRoute: typeof GetProviderRouteImport
      parentRoute: typeof GetRoute
    }
    '/go/$assignmentId': {
      id: '/go/$assignmentId'
      path: '/go/$assignmentId'
      fullPath: '/go/$assignmentId'
      preLoaderRoute: typeof GoAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$token': {
      id: '/i/$token'
      path: '/i/$token'
      fullPath: '/i/$token'
      preLoaderRoute: typeof ITokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/': {
      id: '/share/'
      path: '/'
      fullPath: '/share/'
      preLoaderRoute: typeof ShareIndexRouteImport
      parentRoute: typeof ShareRoute
    }
    '/share/$provider': {
      id: '/share/$provider'
      path: '/$provider'
      fullPath: '/share/$provider'
      preLoaderRoute: typeof ShareProviderRouteImport
      parentRoute: typeof ShareRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GetRouteChildren {
  GetProviderRoute: typeof GetProviderRoute
  GetIndexRoute: typeof GetIndexRoute
}

const GetRouteChildren: GetRouteChildren = {
  GetProviderRoute: GetProviderRoute,
  GetIndexRoute: GetIndexRoute,
}

const GetRouteWithChildren = GetRoute._addFileChildren(GetRouteChildren)

interface ShareRouteChildren {
  ShareProviderRoute: typeof ShareProviderRoute
  ShareIndexRoute: typeof ShareIndexRoute
}

const ShareRouteChildren: ShareRouteChildren = {
  ShareProviderRoute: ShareProviderRoute,
  ShareIndexRoute: ShareIndexRoute,
}

const ShareRouteWithChildren = ShareRoute._addFileChildren(ShareRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  DashboardRoute: DashboardRoute,
  GetRoute: GetRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ShareRoute: ShareRouteWithChildren,
  TermsRoute: TermsRoute,
  GoAssignmentIdRoute: GoAssignmentIdRoute,
  ITokenRoute: ITokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
